name: cgs-engine
version: 1.0.0
description: CGS Game Engine
main: gg.scala.cgs.game.CgsEnginePlugin

author: Scala
website: https://scala.gg

depend:
  - Cubed
  - helper
  - Lemon

softdepend:
  - spark
